# Site settings
title: "EGSR"
tagline: "Eurographics Symposium on Rendering 2021"

# Handling Reading
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
permalink: /:categories/:title/
markdown: kramdown

timezone: Europe/Berlin

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Contact
# email: "egsr2020@cs.ucl.ac.uk"

# Social
#facebook: egsr-4668468684?
#twitter: egsr


# Use this for production
sass:
    style: compressed
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]


theme: jekyll-theme-slate

collections:
  session:
    output: true
    sort_by: session_id